version: '3'
services:
  btc-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: btc-tracker
    environment:
      #- DISPLAY=$DISPLAY
      - DISPLAY=host.docker.internal:0.0
      - FONT_PATH=./DS-DIGII.TTF
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix